server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  data-source:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/jobtracker"
    username: root
    password: "123456"
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master/db.changelog-master.yaml

  redis:
    host: localhost
    port: 6379
    password: ""

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

jwt:
  signer-key: 3fc35280eaa58f16073a24ca3c5f0dd2d3ecbb6f89a3f013eba40c91bb775491
  valid-duration: 1800          # 30 phút
  refreshable-duration: 604800  # 7 ngày