databaseChangeLog:
  - changeSet:
      id: create-indexes-application-statuses
      author: namphan
      changes:
        - createIndex:
            indexName: uq_application_statuses_company_name
            tableName: application_statuses
            unique: true
            columns:
              - column:
                  name: company_id
              - column:
                  name: name
        - createIndex:
            indexName: idx_application_statuses_company_active
            tableName: application_statuses
            columns:
              - column:
                  name: company_id
              - column:
                  name: is_active
        - createIndex:
            indexName: idx_application_statuses_status_type
            tableName: application_statuses
            columns:
              - column:
                  name: status_type
        - createIndex:
            indexName: idx_application_statuses_created_at
            tableName: application_statuses
            columns:
              - column:
                  name: created_at
        - createIndex:
            indexName: idx_application_statuses_created_by
            tableName: application_statuses
            columns:
              - column:
                  name: created_by
        - createIndex:
            indexName: idx_application_statuses_updated_by
            tableName: application_statuses
            columns:
              - column:
                  name: updated_by
        - createIndex:
            indexName: idx_application_statuses_deleted_at
            tableName: application_statuses
            columns:
              - column:
                  name: deleted_at

