databaseChangeLog:
  - changeSet:
      id: create-indexes-application-status-history
      author: namphan
      changes:
        - createIndex:
            indexName: idx_application_status_history_application_id
            tableName: application_status_history
            columns:
              - column:
                  name: application_id
        - createIndex:
            indexName: idx_application_status_history_from_status_id
            tableName: application_status_history
            columns:
              - column:
                  name: from_status_id
        - createIndex:
            indexName: idx_application_status_history_to_status_id
            tableName: application_status_history
            columns:
              - column:
                  name: to_status_id
        - createIndex:
            indexName: idx_application_status_history_changed_by
            tableName: application_status_history
            columns:
              - column:
                  name: changed_by
        - createIndex:
            indexName: idx_application_status_history_created_at
            tableName: application_status_history
            columns:
              - column:
                  name: created_at

